
[project]
name = "subkart"
version = "0.1.0"
description = ""
authors = [
    {name = "Kim Leirvik",email = "kim.leirvik@niva.no"}
]
readme = "README.md"
requires-python = ">=3.11,<3.15"
dependencies = [
    "geoalchemy2>=0.18.1",
    "geopandas>=1.1.2",
    "lxml>=6.0.2",
    "matplotlib>=3.10.8",
    "psycopg2-binary>=2.9.11",
    "pyarrow>=23.0.0",
    "rasterio>=1.4.4",
    "scikit-learn==1.7.1",
    "shapely>=2.1.2",
    "sqlalchemy>=2.0.46",
    "xdem>=0.2.2",
    "gcsfs (>=2026.2.0,<2027.0.0)",
]

[tool.poetry.group.dev.dependencies]
isort = "^8.0.0"
black = {extras = ["jupyter"], version = "^26.1.0"}
ipykernel = "^7.2.0"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target_version = ['py310']
include = '\.py$'

[tool.isort]
line_length=120                # corresponds to -w  flag
multi_line_output=3            # corresponds to -m  flag
include_trailing_comma=true    # corresponds to -tc flag
skip_glob = '^((?!py$).)*$'    # this makes sort all Python files