[project]
name = "marint-naturkart-niva"
version = "0.1.0"
description = ""
package-mode = false
authors = [
    {name = "Kim Leirvik",email = "kim.leirvik@niva.no"}
]
readme = "README.md"
requires-python = ">=3.11,<3.15"
dependencies = [
    "geoalchemy2>=0.18.1",
    "geopandas>=1.1.2",
    "ipykernel>=7.1.0",
    "lxml>=6.0.2",
    "matplotlib>=3.10.8",
    "psycopg2-binary>=2.9.11",
    "pyarrow>=23.0.0",
    "rasterio>=1.4.4",
    "scikit-learn==1.7.1",
    "shapely>=2.1.2",
    "sqlalchemy>=2.0.46",
    "xdem>=0.2.2",
]


